apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: assignment3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: duashakeel0/nginx-proxy:latest
        ports:
        - containerPort: 80
